title: Computer Architecture and Operating Systems
description: Course taught at Faculty of Computer Science of Higher School of Economics
theme: jekyll-theme-slate

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax