title: <a href="/hse-acos-course" style="color:inherit;">Computer Architecture and Operating Systems</a>
description: Course taught at Faculty of Computer Science of Higher School of Economics
theme: jekyll-theme-slate

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
